"""
cnn.py
------
1-D Convolutional Neural Network over word embeddings for suicidal
ideation detection (binary classification).

Architecture:
    Embedding lookup → Conv1d (multiple filter sizes) → ReLU → MaxPool
    → Concat → Dropout → Linear → LogSoftmax

Usage:
    python cnn.py -e 10 \
        --train_data data/train.json \
        --val_data   data/val.json   \
        --test_data  data/test.json

Requires word_embedding.pkl (50-d GloVe) generated by preprocess.py.
"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import random
import os
import time
import json
import string
import pickle
from tqdm import tqdm
from argparse import ArgumentParser
from sklearn.metrics import f1_score, precision_score, recall_score, classification_report

# ── Model ─────────────────────────────────────────────────────────────────────

class TextCNN(nn.Module):
    """
    Kim (2014)-style text CNN.
    Multiple filter widths capture different n-gram patterns in parallel;
    max-over-time pooling extracts the strongest signal from each filter.
    """

    def __init__(self, embed_dim: int, num_filters: int = 128,
                 filter_sizes: tuple = (2, 3, 4, 5),
                 output_dim: int = 2, dropout: float = 0.5):
        super(TextCNN, self).__init__()

        # One Conv1d per filter size
        self.convs = nn.ModuleList([
            nn.Conv1d(
                in_channels  = embed_dim,
                out_channels = num_filters,
                kernel_size  = fs
            )
            for fs in filter_sizes
        ])

        self.relu    = nn.ReLU()
        self.dropout = nn.Dropout(dropout)
        # After max-pooling each filter bank we get num_filters values;
        # concatenate across all filter sizes.
        self.fc      = nn.Linear(num_filters * len(filter_sizes), output_dim)
        self.softmax = nn.LogSoftmax(dim=-1)
        self.loss    = nn.NLLLoss()

    def compute_Loss(self, predicted_vector, gold_label):
        return self.loss(predicted_vector, gold_label)

    def forward(self, x):
        """
        x: (1, seq_len, embed_dim)  — batch_size=1 for this training loop
        """
        # → (1, embed_dim, seq_len)  [channels-first for Conv1d]
        x = x.permute(0, 2, 1)

        # Apply each conv, ReLU, then max-pool over the time dimension
        pooled = []
        for conv in self.convs:
            c = self.relu(conv(x))           # (1, num_filters, seq_len - fs + 1)
            p = c.max(dim=2).values          # (1, num_filters)
            pooled.append(p)

        # Concatenate all filter outputs → (1, num_filters * len(filter_sizes))
        cat = torch.cat(pooled, dim=1)
        cat = self.dropout(cat)

        # Linear projection + log-softmax
        out = self.fc(cat)                   # (1, output_dim)
        return self.softmax(out)


# ── Data utilities ────────────────────────────────────────────────────────────

def load_data(train_path, val_path):
    with open(train_path) as f:
        training   = json.load(f)
    with open(val_path) as f:
        validation = json.load(f)

    def parse(records):
        return [(elt["text"].split(), int(elt["stars"]) - 1)
                for elt in records]

    return parse(training), parse(validation)


def load_test(test_path):
    with open(test_path) as f:
        test = json.load(f)
    return [(elt["text"].split(), int(elt["stars"]) - 1) for elt in test]


def words_to_tensor(input_words, word_embedding):
    """
    Returns a (1, seq_len, embed_dim) float tensor.
    Handles empty sequences gracefully by returning a single unk vector.
    """
    cleaned = " ".join(input_words)
    cleaned = cleaned.translate(str.maketrans("", "", string.punctuation)).split()
    vectors = [
        word_embedding[w.lower()] if w.lower() in word_embedding
        else word_embedding["unk"]
        for w in cleaned
    ]
    if len(vectors) == 0:
        vectors = [word_embedding["unk"]]
    return torch.tensor(np.array(vectors), dtype=torch.float32).unsqueeze(0)
    # (1, seq_len, embed_dim)


# ── Evaluation ────────────────────────────────────────────────────────────────

def evaluate(model, data, word_embedding, min_len: int = 5):
    model.eval()
    correct, total = 0, 0
    all_preds, all_labels = [], []

    with torch.no_grad():
        for input_words, gold_label in tqdm(data, desc="  eval", leave=False):
            vectors = words_to_tensor(input_words, word_embedding)

            # Skip sequences shorter than the largest filter size
            if vectors.shape[1] < min_len:
                pad_len = min_len - vectors.shape[1]
                unk_vec = torch.tensor(word_embedding["unk"]).unsqueeze(0).unsqueeze(0)
                padding = unk_vec.expand(1, pad_len, -1)
                vectors = torch.cat([vectors, padding], dim=1)

            output = model(vectors)
            pred   = torch.argmax(output).item()
            correct += int(pred == gold_label)
            total   += 1
            all_preds.append(pred)
            all_labels.append(gold_label)

    accuracy  = correct / total
    f1        = f1_score(all_labels, all_preds, average="binary")
    precision = precision_score(all_labels, all_preds, average="binary", zero_division=0)
    recall    = recall_score(all_labels, all_preds, average="binary", zero_division=0)
    return accuracy, f1, precision, recall, all_preds, all_labels


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("-e",  "--epochs",      type=int,   required=True)
    parser.add_argument("--train_data",  required=True)
    parser.add_argument("--val_data",    required=True)
    parser.add_argument("--test_data",   default=None)
    parser.add_argument("--embedding",   default="word_embedding.pkl")
    parser.add_argument("--num_filters", type=int, default=128,
                        help="Number of filters per filter size (default 128)")
    parser.add_argument("--save_model",  default=None)
    args = parser.parse_args()

    random.seed(42)
    torch.manual_seed(42)

    # ── Embeddings ──
    print("=" * 50)
    print(f"Loading word embeddings from {args.embedding} ...")
    word_embedding = pickle.load(open(args.embedding, "rb"))
    embed_dim      = next(iter(word_embedding.values())).shape[0]
    print(f"  Embed dim : {embed_dim}  |  Vocab : {len(word_embedding)}")

    # ── Data ──
    print("Loading data ...")
    train_data, valid_data = load_data(args.train_data, args.val_data)
    print(f"  Train : {len(train_data)}   Val : {len(valid_data)}")

    # ── Model ──
    filter_sizes = (2, 3, 4, 5)
    model        = TextCNN(embed_dim      = embed_dim,
                           num_filters    = args.num_filters,
                           filter_sizes   = filter_sizes,
                           output_dim     = 2,
                           dropout        = 0.5)
    optimizer    = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-5)
    scheduler    = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="max",
                                                         patience=2, factor=0.5)
    print(f"Model : TextCNN  filters={args.num_filters}  sizes={filter_sizes}")
    print("=" * 50)

    MIN_SEQ = max(filter_sizes)   # minimum sequence length for CNN
    best_val_f1 = 0.0

    for epoch in range(args.epochs):
        model.train()
        random.shuffle(train_data)
        correct, total = 0, 0
        loss_sum       = 0.0
        start          = time.time()

        for input_words, gold_label in tqdm(train_data, desc=f"Epoch {epoch+1}"):
            vectors = words_to_tensor(input_words, word_embedding)

            # Pad very short sequences
            if vectors.shape[1] < MIN_SEQ:
                pad_len = MIN_SEQ - vectors.shape[1]
                unk_vec = torch.tensor(word_embedding["unk"]).unsqueeze(0).unsqueeze(0)
                padding = unk_vec.expand(1, pad_len, -1)
                vectors = torch.cat([vectors, padding], dim=1)

            optimizer.zero_grad()
            output   = model(vectors)
            loss     = model.compute_Loss(output, torch.tensor([gold_label]))
            loss.backward()
            optimizer.step()

            pred     = torch.argmax(output).item()
            correct += int(pred == gold_label)
            total   += 1
            loss_sum += loss.item()

        train_acc = correct / total
        val_acc, val_f1, val_prec, val_rec, _, _ = evaluate(
            model, valid_data, word_embedding, min_len=MIN_SEQ)
        scheduler.step(val_f1)

        elapsed = time.time() - start
        print(f"\nEpoch {epoch+1:>2} | "
              f"Loss {loss_sum/total:.4f} | "
              f"Train Acc {train_acc:.4f} | "
              f"Val Acc {val_acc:.4f}  F1 {val_f1:.4f}  "
              f"P {val_prec:.4f}  R {val_rec:.4f} | {elapsed:.1f}s")

        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            if args.save_model:
                torch.save(model.state_dict(), args.save_model)
                print(f"  ✓ Best model saved → {args.save_model}")

    # ── Test ──
    if args.test_data:
        print("\n" + "=" * 50)
        print("Evaluating on test set ...")
        test_data = load_test(args.test_data)
        t_acc, t_f1, t_prec, t_rec, preds, labels = evaluate(
            model, test_data, word_embedding, min_len=MIN_SEQ)
        print(f"Test  Acc {t_acc:.4f}  F1 {t_f1:.4f}  "
              f"Precision {t_prec:.4f}  Recall {t_rec:.4f}")
        print("\nDetailed report:")
        print(classification_report(labels, preds,
                                    target_names=["non-suicidal", "suicidal"]))

        os.makedirs("results", exist_ok=True)
        with open("results/cnn_test.out", "w") as f:
            for p in preds:
                f.write(str(p) + "\n")
        print("Predictions written → results/cnn_test.out")
