"""
rnn.py
------
RNN / LSTM model with pre-trained word embeddings (GloVe / Word2Vec)
for suicidal ideation detection (binary classification).

Usage (RNN):
    python rnn.py -hd 128 -e 10 \
        --train_data data/train.json \
        --val_data   data/val.json   \
        --test_data  data/test.json  \
        --model_type rnn

Usage (LSTM):
    python rnn.py -hd 128 -e 10 \
        --train_data data/train.json \
        --val_data   data/val.json   \
        --test_data  data/test.json  \
        --model_type lstm

Requires word_embedding.pkl (50-d GloVe) generated by preprocess.py.
"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import random
import os
import time
import json
import string
import pickle
from tqdm import tqdm
from argparse import ArgumentParser
from sklearn.metrics import f1_score, precision_score, recall_score, classification_report

unk = '<UNK>'


# ── Models ────────────────────────────────────────────────────────────────────

class RNN(nn.Module):
    """Vanilla RNN — processes a variable-length sequence of word vectors."""

    def __init__(self, input_dim: int, h: int, output_dim: int = 2):
        super(RNN, self).__init__()
        self.h           = h
        self.numOfLayer  = 1
        self.rnn         = nn.RNN(input_dim, h, self.numOfLayer,
                                  nonlinearity='tanh', batch_first=False)
        self.dropout     = nn.Dropout(p=0.3)
        self.W           = nn.Linear(h, output_dim)
        self.softmax     = nn.LogSoftmax(dim=-1)
        self.loss        = nn.NLLLoss()

    def compute_Loss(self, predicted_vector, gold_label):
        return self.loss(predicted_vector, gold_label)

    def forward(self, inputs):
        # inputs: (seq_len, 1, input_dim)
        # hidden: (num_layers, 1, h)
        _, hidden        = self.rnn(inputs)

        # Take the final hidden state, remove batch dim → (1, h)
        hidden           = hidden[-1]                    # (1, h)
        hidden           = self.dropout(hidden)

        # Linear projection → (1, output_dim)
        output           = self.W(hidden)

        # Log-probability distribution
        predicted_vector = self.softmax(output)
        return predicted_vector


class LSTM(nn.Module):
    """LSTM — better long-range dependency modelling than vanilla RNN."""

    def __init__(self, input_dim: int, h: int, output_dim: int = 2,
                 num_layers: int = 1, bidirectional: bool = False):
        super(LSTM, self).__init__()
        self.h             = h
        self.bidirectional = bidirectional
        self.lstm          = nn.LSTM(input_dim, h, num_layers,
                                     batch_first=False,
                                     bidirectional=bidirectional,
                                     dropout=0.3 if num_layers > 1 else 0.0)
        factor             = 2 if bidirectional else 1
        self.dropout       = nn.Dropout(p=0.3)
        self.W             = nn.Linear(h * factor, output_dim)
        self.softmax       = nn.LogSoftmax(dim=-1)
        self.loss          = nn.NLLLoss()

    def compute_Loss(self, predicted_vector, gold_label):
        return self.loss(predicted_vector, gold_label)

    def forward(self, inputs):
        # inputs: (seq_len, 1, input_dim)
        _, (hidden, _)   = self.lstm(inputs)

        if self.bidirectional:
            # Concatenate forward and backward final hidden states
            hidden       = torch.cat((hidden[-2], hidden[-1]), dim=1)  # (1, 2h)
        else:
            hidden       = hidden[-1]                                   # (1, h)

        hidden           = self.dropout(hidden)
        output           = self.W(hidden)
        predicted_vector = self.softmax(output)
        return predicted_vector


# ── Data loading ──────────────────────────────────────────────────────────────

def load_data(train_path, val_path):
    with open(train_path) as f:
        training   = json.load(f)
    with open(val_path) as f:
        validation = json.load(f)

    def parse(records):
        return [(elt["text"].split(), int(elt["stars"]) - 1)
                for elt in records]

    return parse(training), parse(validation)


def load_test(test_path):
    with open(test_path) as f:
        test = json.load(f)
    return [(elt["text"].split(), int(elt["stars"]) - 1) for elt in test]


def words_to_tensor(input_words, word_embedding):
    """Convert a list of words to a (seq_len, 1, embed_dim) tensor."""
    # Strip punctuation and lower-case
    cleaned = " ".join(input_words)
    cleaned = cleaned.translate(str.maketrans("", "", string.punctuation)).split()
    vectors = [
        word_embedding[w.lower()] if w.lower() in word_embedding
        else word_embedding["unk"]
        for w in cleaned
    ]
    if len(vectors) == 0:          # edge case: empty post after cleaning
        vectors = [word_embedding["unk"]]
    return torch.tensor(np.array(vectors), dtype=torch.float32).unsqueeze(1)
    # shape: (seq_len, 1, embed_dim)


# ── Evaluation helper ─────────────────────────────────────────────────────────

def evaluate(model, data, word_embedding):
    model.eval()
    correct, total = 0, 0
    all_preds, all_labels = [], []

    with torch.no_grad():
        for input_words, gold_label in tqdm(data, desc="  eval", leave=False):
            vectors      = words_to_tensor(input_words, word_embedding)
            output       = model(vectors)
            pred         = torch.argmax(output).item()
            correct     += int(pred == gold_label)
            total       += 1
            all_preds.append(pred)
            all_labels.append(gold_label)

    accuracy  = correct / total
    f1        = f1_score(all_labels, all_preds, average="binary")
    precision = precision_score(all_labels, all_preds, average="binary", zero_division=0)
    recall    = recall_score(all_labels, all_preds, average="binary", zero_division=0)
    return accuracy, f1, precision, recall, all_preds, all_labels


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("-hd", "--hidden_dim", type=int, required=True)
    parser.add_argument("-e",  "--epochs",     type=int, required=True)
    parser.add_argument("--train_data",  required=True)
    parser.add_argument("--val_data",    required=True)
    parser.add_argument("--test_data",   default=None)
    parser.add_argument("--model_type",  default="lstm",
                        choices=["rnn", "lstm"],
                        help="Which architecture to use (default: lstm)")
    parser.add_argument("--bidirectional", action="store_true",
                        help="Use bidirectional LSTM (ignored for rnn)")
    parser.add_argument("--embedding",   default="word_embedding.pkl",
                        help="Path to pickled word embedding dict")
    parser.add_argument("--save_model",  default=None)
    parser.add_argument("--do_train",    action="store_true")
    args = parser.parse_args()

    random.seed(42)
    torch.manual_seed(42)

    # ── Load embeddings ──
    print("=" * 50)
    print(f"Loading word embeddings from {args.embedding} ...")
    word_embedding = pickle.load(open(args.embedding, "rb"))
    embed_dim      = next(iter(word_embedding.values())).shape[0]
    print(f"  Embed dim : {embed_dim}   |   Vocab : {len(word_embedding)}")

    # ── Load data ──
    print("Loading data ...")
    train_data, valid_data = load_data(args.train_data, args.val_data)
    print(f"  Train : {len(train_data)}   Val : {len(valid_data)}")

    # ── Build model ──
    if args.model_type == "lstm":
        model = LSTM(embed_dim, args.hidden_dim, output_dim=2,
                     bidirectional=args.bidirectional)
        print(f"Model : {'Bidirectional ' if args.bidirectional else ''}LSTM  "
              f"hidden={args.hidden_dim}")
    else:
        model = RNN(embed_dim, args.hidden_dim, output_dim=2)
        print(f"Model : RNN  hidden={args.hidden_dim}")

    optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-5)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="max",
                                                      patience=2, factor=0.5)

    minibatch_size    = 16
    best_val_f1       = 0.0
    last_val_accuracy = 0.0
    last_train_acc    = 0.0
    epoch             = 0

    print("=" * 50)

    while epoch < args.epochs:
        random.shuffle(train_data)
        model.train()
        correct, total = 0, 0
        loss_total, loss_count = 0.0, 0
        N     = len(train_data)
        start = time.time()

        print(f"Training epoch {epoch + 1} ...")
        for mb in tqdm(range(N // minibatch_size), desc=f"  Epoch {epoch+1}"):
            optimizer.zero_grad()
            loss = None
            for i in range(minibatch_size):
                input_words, gold_label = train_data[mb * minibatch_size + i]
                vectors     = words_to_tensor(input_words, word_embedding)
                output      = model(vectors)
                ex_loss     = model.compute_Loss(output.view(1, -1),
                                                 torch.tensor([gold_label]))
                pred        = torch.argmax(output).item()
                correct    += int(pred == gold_label)
                total      += 1
                loss = ex_loss if loss is None else loss + ex_loss

            loss = loss / minibatch_size
            loss_total += loss.item()
            loss_count += 1
            loss.backward()
            # Gradient clipping to prevent exploding gradients (especially RNN)
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
            optimizer.step()

        train_acc = correct / total
        avg_loss  = loss_total / loss_count

        # ── Validation ──
        val_acc, val_f1, val_prec, val_rec, _, _ = evaluate(
            model, valid_data, word_embedding)
        scheduler.step(val_f1)

        elapsed = time.time() - start
        print(f"  Loss {avg_loss:.4f} | Train Acc {train_acc:.4f} | "
              f"Val Acc {val_acc:.4f}  F1 {val_f1:.4f}  "
              f"P {val_prec:.4f}  R {val_rec:.4f} | {elapsed:.1f}s")

        # Save best checkpoint
        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            if args.save_model:
                torch.save(model.state_dict(), args.save_model)
                print(f"  ✓ Best model saved → {args.save_model}  (F1={best_val_f1:.4f})")

        # Early-stopping: stop when val acc drops while train acc keeps climbing
        if val_acc < last_val_accuracy and train_acc > last_train_acc:
            print("\nEarly stopping triggered (overfitting detected).")
            print(f"Best validation accuracy : {last_val_accuracy:.4f}")
            break

        last_val_accuracy = val_acc
        last_train_acc    = train_acc
        epoch            += 1

    # ── Test ──
    if args.test_data:
        print("\n" + "=" * 50)
        print("Evaluating on test set ...")
        test_data = load_test(args.test_data)
        t_acc, t_f1, t_prec, t_rec, preds, labels = evaluate(
            model, test_data, word_embedding)
        print(f"Test  Acc {t_acc:.4f}  F1 {t_f1:.4f}  "
              f"Precision {t_prec:.4f}  Recall {t_rec:.4f}")
        print("\nDetailed report:")
        print(classification_report(labels, preds,
                                    target_names=["non-suicidal", "suicidal"]))

        os.makedirs("results", exist_ok=True)
        with open("results/rnn_test.out", "w") as f:
            for p in preds:
                f.write(str(p) + "\n")
        print("Predictions written → results/rnn_test.out")
